apiVersion: v2
name: goldpinger
description: Goldpinger component for Karavel
type: application
version: 1.1.0-SNAPSHOT
appVersion: 3.3.0
maintainers:
  - name: MatteoJoliveau
    email: matteo.joliveau@mikamai.com

home: https://github.com/bloomberg/goldpinger
sources:
  - https://github.com/bloomberg/goldpinger
  - https://github.com/karavel-io/platform

annotations:
  grafana.enable: grafana
  prometheus.enable: prometheus
